dbt_impala_demo:
  outputs:
    dev_cia_cdp:
     type: impala
     host: "{{ env_var('DBT_HOST') }}"
     http_path: "{{ env_var('DBT_HTTP_PATH') }}"
     port: 443
     auth_type: ldap
     use_http_transport: true
     use_ssl: true
     username: "{{ env_var('DBT_USER') }}"
     password: "{{ env_var('DBT_PASSWORD') }}"
     dbname: "{{ env_var('DBT_DBNAME') }}"
     schema: "{{ env_var('DBT_SCHEMA') }}"
  target: dev_cia_cdp
